http://deeplearning.net/software/theano/tutorial/adding.html

### Adding two scalars

In [4]:
import theano.tensor as T
from theano import function
x = T.dscalar('x')
y = T.dscalar('y')
z = x + y
f = function([x,y],z)

In [5]:
f(2,3)

array(5.0)

In [6]:
f(16.3, 12.1)

array(28.4)

In [7]:
type(x)

theano.tensor.var.TensorVariable

In [8]:
x.type

TensorType(float64, scalar)

In [10]:
T.dscalar

TensorType(float64, scalar)

In [11]:
x.type is T.dscalar

True

In [12]:
z = x + y

In [13]:
from theano import pp
print pp(z)

(x + y)


In [14]:
f = function([x,y],z)

###Can also use eval()

In [18]:
import theano.tensor as T
x = T.dscalar('x')
y = T.dscalar('y')
z = x + y
z.eval({x:16.3,y:12.1})

array(28.4)

### Adding two matrices

In [19]:
x = T.dmatrix('x')
y = T.dmatrix('y')
z = x + y
f = function([x,y],z)

In [20]:
f([[1,2],[3,4]], [[10,20],[30,40]])

array([[ 11.,  22.],
       [ 33.,  44.]])

In [21]:
import numpy
f(numpy.array([[1,2],[3,4]]), numpy.array([[10,20], [30,40]]))

array([[ 11.,  22.],
       [ 33.,  44.]])

These types are available
- byte: bscalar, bvector, bmatrix, brow, bcol, btensor3, btensor4
- 16-bit integers: wscalar, wvector, wmatrix, wrow, wcol, wtensor3, wtensor4
- 32-bit integers: iscalar, ivector, imatrix, irow, icol, itensor3, itensor4
- 64-bit integers: lscalar, lvector, lmatrix, lrow, lcol, ltensor3, ltensor4
- float: fscalar, fvector, fmatrix, frow, fcol, ftensor3, ftensor4
- double: dscalar, dvector, dmatrix, drow, dcol, dtensor3, dtensor4
- complex: cscalar, cvector, cmatrix, crow, ccol, ctensor3, ctensor4

### Exercise

In [23]:
import theano
a = theano.tensor.vector()    # declare variable
out = a + a ** 18             # build symbolic expression
f = theano.function([a], out) # compile function
print f([0,1,2])              # prints `array([0,2,1026])`

[  0.00000000e+00   2.00000000e+00   2.62146000e+05]


Modify and execute this code to compute this expression: $\text{a ** 2 + b ** 2 + 2 * a * b.}$

#### Solution

In [32]:
import theano
import theano.tensor as T
a = T.dscalar()      # declare variable
b = T.dscalar()      # declare another variable
out = a**2 + b**2 + 2*a*b       # build symbolic expression
f = theano.function([a,b], out) # compile function
print f(2,3)  

25.0


In [33]:
import theano
import theano.tensor as T
a = T.vector()      # declare variable
b = T.vector()      # declare another variable
out = a**2 + b**2 + 2*a*b       # build symbolic expression
f = theano.function([a,b], out) # compile function
print f([2,3],[3,4])  

[ 25.  49.]
